util.py: Don't open file in binary mode when writing configparser file
Avoids:
	TypeError: 'str' does not support the buffer interface

Signed-off-by: Andrei Gherzan <andrei@resin.io>